<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827090029 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE friendships (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, friend_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E0A8B7CAA76ED395 ON friendships (user_id)');
        $this->addSql('CREATE INDEX IDX_E0A8B7CA6A5458E8 ON friendships (friend_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_friendship_pair ON friendships (user_id, friend_id)');
        $this->addSql('ALTER TABLE friendships ADD CONSTRAINT FK_E0A8B7CAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE friendships ADD CONSTRAINT FK_E0A8B7CA6A5458E8 FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE friendships DROP CONSTRAINT FK_E0A8B7CAA76ED395');
        $this->addSql('ALTER TABLE friendships DROP CONSTRAINT FK_E0A8B7CA6A5458E8');
        $this->addSql('DROP TABLE friendships');
    }
}
