<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827091154 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blocks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, blocker_id INT NOT NULL, blocked_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CEED9578548D5975 ON blocks (blocker_id)');
        $this->addSql('CREATE INDEX IDX_CEED957821FF5136 ON blocks (blocked_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_block_pair ON blocks (blocker_id, blocked_id)');
        $this->addSql('ALTER TABLE blocks ADD CONSTRAINT FK_CEED9578548D5975 FOREIGN KEY (blocker_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE blocks ADD CONSTRAINT FK_CEED957821FF5136 FOREIGN KEY (blocked_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blocks DROP CONSTRAINT FK_CEED9578548D5975');
        $this->addSql('ALTER TABLE blocks DROP CONSTRAINT FK_CEED957821FF5136');
        $this->addSql('DROP TABLE blocks');
    }
}
