<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260826195428 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE friend_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sender_id INT NOT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EC63B01BF624B39D ON friend_requests (sender_id)');
        $this->addSql('CREATE INDEX IDX_EC63B01BE92F8F78 ON friend_requests (recipient_id)');
        $this->addSql('CREATE INDEX idx_fr_recipient_status ON friend_requests (recipient_id, status)');
        $this->addSql('CREATE INDEX idx_fr_sender_status ON friend_requests (sender_id, status)');
        $this->addSql('ALTER TABLE friend_requests ADD CONSTRAINT FK_EC63B01BF624B39D FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE friend_requests ADD CONSTRAINT FK_EC63B01BE92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE UNIQUE INDEX uniq_pending_friend_request
            ON friend_requests (sender_id, recipient_id)
            WHERE status = \'pending\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX uniq_pending_friend_request');

        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE friend_requests DROP CONSTRAINT FK_EC63B01BF624B39D');
        $this->addSql('ALTER TABLE friend_requests DROP CONSTRAINT FK_EC63B01BE92F8F78');
        $this->addSql('DROP TABLE friend_requests');
    }
}
